version: "3.7"
services:
  web:
    container_name: math-prob
    volumes:
      - ./pts:/code/pts
    build: .
    ports:
      - "5000:5000"
#networks:
#  default:
#    external:
#      name: nginxnet
