version: "3.7"
services:
  web:
    container_name: math-prob
    volumes:
      - points:/code/pts
    build: .
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
volumes:
  points:
#networks:
#  default:
#    external:
#      name: nginxnet
