version: "3.7"
services:
  web:
    container_name: math-prob
    restart: unless-stopped
    volumes:
      - data:/code/pts
    build: .
    ports:
      - "5000:5000"
volumes:
  data:
#networks:
#  default:
#    external:
#      name: nginxnet
